export const METRIC_DIRECTIONS = {
  winRate: 'higher',
  averageFinalVictoryPoints: 'higher',
  averageRoundsToWin: 'lower',
  taskSuccessRate: 'higher',
  averageLatencyPerTurn: 'lower',
};

export const BENCHMARK_WEIGHTS = {
  winRate: 0.3,
  averageFinalVictoryPoints: 0.15,
  averageRoundsToWin: 0.15,
  taskSuccessRate: 0.3,
  averageLatencyPerTurn: 0.1,
};

export const TASK_CATEGORIES = {
  shortTerm: 'Short-Term',
  mediumTerm: 'Medium-Term',
  longTerm: 'Long-Term',
};

export const BENCHMARK_TASKS = [
  {
    id: 'settlement-location-selection',
    name: 'Settlement Location Selection',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose where to place a settlement after committing to the settlement build.',
    scoring: '0.40 production + 0.25 diversity + 0.20 expansionAccess + 0.15 portSynergy',
  },
  {
    id: 'road-placement-direction',
    name: 'Road Placement Direction',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose the strongest legal road placement for frontier reach, settlement follow-up value, and blocking.',
    scoring: '0.25 futureReachability + 0.20 reachableIntersectionValue + 0.10 blockingValue + 0.25 settlementTargetValue + 0.15 extensionValue + 0.05 cycleAvoidance',
  },
  {
    id: 'knight-card-playing-decision',
    name: 'Knight Card Playing Decision',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Decide whether to play a Knight now instead of holding it.',
    scoring: '0.45 robberThreatLevel + 0.35 resourceNeed + 0.20 armyProgressRatio',
  },
  {
    id: 'year-of-plenty-card-playing-decision',
    name: 'Year of Plenty Card Playing Decision',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose the two resources to take from Year of Plenty.',
    scoring: '0.50 buildUnlock + 0.35 resourceScarcity + 0.15 longtermDiversityGain',
  },
  {
    id: 'monopoly-card-playing-decision',
    name: 'Monopoly Card Playing Decision',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose which resource to call when playing Monopoly.',
    scoring: '0.55 estimatedOpponentHoldings + 0.30 personalResourceNeed + 0.15 buildUnlock',
  },
  {
    id: 'road-building-card-playing-decision',
    name: 'Road Building Card Playing Decision',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Decide when using Road Building creates enough immediate value to justify the play.',
    scoring: 'Option-ratio',
  },
  {
    id: 'robber-victim-selection',
    name: 'Robber Victim Selection',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose which eligible player to target after moving the robber.',
    scoring: 'Option-ratio',
  },
  {
    id: 'robber-placement',
    name: 'Robber Placement',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose the hex that best hurts opponents without backfiring.',
    scoring: '0.35 hurtLeader + 0.30 productionDamage + 0.20 theftValue + 0.15 selfHarmAvoidance',
  },
  {
    id: 'accept-or-reject-trade-offers',
    name: 'Accept or Reject Trade Offers',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Evaluate whether an incoming trade improves position enough to accept.',
    scoring: 'Accept iff plan-aware trade quality >= 0.70; trade quality = 0.35 legality + 0.45 selfGain + 0.15 (1 - leaderPenalty) + 0.05 (1 - fairnessPenalty)',
  },
  {
    id: 'generate-trade-offers',
    name: 'Generate Trade Offers',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Construct trade proposals that improve the agent position while limiting leader help.',
    scoring: '0.35 legality + 0.45 selfGain + 0.15 (1 - leaderPenalty) + 0.05 (1 - fairnessPenalty)',
  },
  {
    id: 'select-targeted-trade-partner',
    name: 'Select Targeted Trade Partner',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Choose which specific opponent is the best partner for a targeted trade.',
    scoring: 'Option-ratio',
  },
  {
    id: 'generate-counter-trade-offer',
    name: 'Generate Counter Trade Offer',
    category: 'shortTerm',
    difficulty: 'easy',
    description: 'Construct a stronger counteroffer in response to an incoming trade.',
    scoring: '0.35 legality + 0.45 selfGain + 0.15 (1 - leaderPenalty) + 0.05 (1 - fairnessPenalty)',
  },
  {
    id: 'build-vs-save-decision',
    name: 'Build vs Save Decision',
    category: 'mediumTerm',
    difficulty: 'medium',
    description: 'Decide whether to spend resources now or hold for a better future turn.',
    scoring: 'Option-ratio',
  },
  {
    id: 'city-vs-settlement-vs-road-prioritization',
    name: 'City vs Settlement vs Road Prioritization',
    category: 'mediumTerm',
    difficulty: 'medium',
    description: 'Choose the best build path from the current hand and board state.',
    scoring: 'Option-ratio',
  },
  {
    id: 'development-card-purchase-decision',
    name: 'Development Card Purchase Decision',
    category: 'mediumTerm',
    difficulty: 'medium',
    description: 'Decide whether buying a development card is the strongest current spend.',
    scoring: 'Option-ratio using dev-card base score with army-race bonus, held-card congestion penalty, and expansion-pressure penalty',
  },
  {
    id: 'discard-strategy-after-seven',
    name: 'Discard Strategy After Seven',
    category: 'mediumTerm',
    difficulty: 'medium',
    description: 'Choose the discard set that preserves the strongest retained hand, including off-turn seven-roll discards.',
    scoring: 'RetainedHandValue / BestRetainedValue',
  },
  {
    id: 'bank-trade-decision',
    name: 'Bank Trade Decision',
    category: 'mediumTerm',
    difficulty: 'medium',
    description: 'Decide whether and how to trade with the bank or a port.',
    scoring: '0.50 resourceValueDelta + 0.30 buildUnlock + 0.20 opportunityCost',
  },
  {
    id: 'initial-settlement-location-selection',
    name: 'Initial Settlement Location Selection',
    category: 'longTerm',
    difficulty: 'difficult',
    description: 'Choose the opening settlement location with the best long-term trajectory.',
    scoring: '0.40 production + 0.25 diversity + 0.20 expansionAccess + 0.15 portSynergy',
  },
  {
    id: 'decide-pursue-longest-road',
    name: 'Decide Pursue Longest Road',
    category: 'longTerm',
    difficulty: 'difficult',
    description: 'Decide whether contesting or extending Longest Road is worth the investment.',
    scoring: '0.40 roadProgressRatio + 0.30 opponentRoadGap + 0.20 resourceAffordability + 0.10 VPImpact',
  },
  {
    id: 'decide-pursue-largest-army',
    name: 'Decide Pursue Largest Army',
    category: 'longTerm',
    difficulty: 'difficult',
    description: 'Decide whether to pursue Largest Army through development-card play.',
    scoring: '0.40 knightCardRatio + 0.30 opponentArmyGap + 0.20 devCardAffordability + 0.10 VPImpact',
  },
];

export function getTaskDefinition(taskId) {
  return BENCHMARK_TASKS.find(task => task.id === taskId) || null;
}
